# Generated by Django 3.1.7 on 2021-03-20 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientpage', '0004_auto_20210227_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonationDrives',
            new_name='Locations',
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
