# Generated by Django 3.1.7 on 2021-03-20 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientpage', '0006_commentsfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsfield',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='clientpage.locations'),
        ),
        migrations.AlterField(
            model_name='commentsfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
