# Generated by Django 3.1.7 on 2021-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0007_auto_20210320_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='FOMO',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='locations',
            name='locationtype',
            field=models.CharField(choices=[('tourist', 'tourist'), ('resteraunt', 'resteraunts')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='youtubevideo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
