# Generated by Django 3.1.7 on 2021-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0008_auto_20210321_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='FOMO',
            field=models.FloatField(default=100),
        ),
    ]
